# Configuración del servidor y Eureka
spring.application.name=ms-usuarios
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuración de Base de Datos MySQL
# Si usas el puerto por defecto es 3306, si lo cambiaste en XAMPP usa 3307
spring.datasource.url=jdbc:mysql://localhost:3306/reservas_usuarios?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect